apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notiflex-api
  namespace: enterprise
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: notiflex-api
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
