prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

grafana:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  adminPassword: admin
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
